<a href="https://colab.research.google.com/github/18K41A04B4/Assignment/blob/master/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Read mobile dataset using pandas, and preprocess it (fill null values)

2. Draw correlation graph for mobile price with all attributes.

3.Compute outer product of 2 vectors. Eg: original matrix: [[1, 0], [0, 1]] [[1, 2], [3, 4]] Outer product of the said two vectors: [[1 2 3 4] [0 0 0 0] [0 0 0 0] [1 2 3 4]]

In [6]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result = np.outer(p, q)
print("Outer product of the said two vectors:")
print(result)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Outer product of the said two vectors:
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


4. Write a NumPy program to compute the condition number of a given matrix. Original matrix: [[1 2] [3 4]]
Condition number of the said matrix:14.9330343737 



In [5]:
import numpy as np
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.cond(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Condition number of the said matrix:
14.933034373659268


5. write a NumPy program to compute the sum of the diagonal element of a given array(matrix).





In [4]:
import numpy as np
m = np.arange(8).reshape(2,4)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2 3]
 [4 5 6 7]]
Condition number of the said matrix:
5
